networks:
  ms:
    name: ms-network
    driver: bridge
    external: true

services:
  back_1:
    build:
      context: .
    container_name: cambio_01
    image: img_cambio_java
    ports:
      - "8001:8000"
    expose:
      - 8001
    environment:
      HOST_DB: ${HOST_DB}
      USER_DB: ${USER_DB}
      PASSWORD_DB: ${PASSWORD_DB}
      PORT: 8001
      HOST_EUREKA: eureka
      REDIS: redis
      REDIS_PORT: 6379
      SECRET: cambio-ms-rotas-madri
    networks:
      - ms

  back_2:
    build:
      context: .
    container_name: cambio_02
    image: img_cambio_java
    ports:
      - "8002:8000"
    expose:
      - 8002
    environment:
      HOST_DB: ${HOST_DB}
      USER_DB: ${USER_DB}
      PASSWORD_DB: ${PASSWORD_DB}
      PORT: 8002
      HOST_EUREKA: eureka
      REDIS: redis
      REDIS_PORT: 6379
      SECRET: cambio-ms-rotas-madri
    networks:
      - ms