networks:
  ms:
    name: ms-network
    driver: bridge
    external: true

services:
  db:
    container_name: db_cambio
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${CAMBIO_USER_DB}
      POSTGRES_PASSWORD: ${CAMBIO_PASSWORD_DB}
      POSTGRES_DB: cambio_server
    ports:
      - "5003:5432"
    networks:
      - ms

  back_1:
    build:
      context: .
    container_name: cambio_01
    image: img_cambio_java
    ports:
      - "8001:8000"
    expose:
      - 8001
    environment:
      USER_DB: ${CAMBIO_USER_DB}
      PASSWORD_DB: ${CAMBIO_PASSWORD_DB}
      PORT_DB: 5432
      PORT: 8001
      HOST_EUREKA: eureka
      REDIS: redis
      REDIS_PORT: 6379
      SECRET: cambio-ms-rotas-madri
    networks:
      - ms
    depends_on:
      db:
        condition: service_started

  back_2:
    build:
      context: .
    container_name: cambio_02
    image: img_cambio_java
    ports:
      - "8002:8000"
    expose:
      - 8002
    environment:
      USER_DB: ${CAMBIO_USER_DB}
      PASSWORD_DB: ${CAMBIO_PASSWORD_DB}
      PORT_DB: 5432
      PORT: 8002
      HOST_EUREKA: eureka
      REDIS: redis
      REDIS_PORT: 6379
      SECRET: cambio-ms-rotas-madri
    networks:
      - ms
    depends_on:
      db:
        condition: service_started