networks:
  ms:
    name: ms-network
    driver: bridge
    external: true

services:
  db:
    container_name: db_cambio
    image: postgres:14.0-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cambio_server
    ports:
      - "5003:5432"
    networks:
      - ms
