server:
  port: ${PORT}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${HOST_EUREKA}:8761/eureka

spring:
  application:
    name: cambio-service

  datasource:
    url: jdbc:postgresql://ep-floral-pond-b4t0xtf4-pooler.c-6.us-east-2.aws.neon.tech?sslmode=require&channelBinding=require
    username: ${CAMBIO_USER_DB}
    password: ${CAMBIO_PASSWORD_DB}

  flyway:
    url: jdbc:postgresql://ep-floral-pond-b4t0xtf4-pooler.c-6.us-east-2.aws.neon.tech/cambio?sslmode=require&channelBinding=require
    schemas: cambio_server
    user: ${CAMBIO_USER_DB}
    password: ${CAMBIO_PASSWORD_DB}

  sql:
    init:
      mode: always
      encoding: utf-8

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  cache:
    type: redis

security:
  jwt:
    public-key: classpath:keys/public.pem
    secret: ${SECRET}