server:
  port: ${PORT}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${HOST_EUREKA}:8761/eureka

spring:
  application:
    name: cambio-service

  datasource:
    url: jdbc:postgresql://${DATA_BASE}:${PORT_DB}/cambio_server
    username: postgres
    password: postgres

  flyway:
    url: jdbc:postgresql://${DATA_BASE}:${PORT_DB}/cambio_server
    schemas: cambio
    user: postgres
    password: postgres

  sql:
    init:
      mode: always
      encoding: utf-8

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
